blockchain:
  type: "ganache"  # ganache | kaleido
  network:
    #rpcEndpoint: "https://k0y4s2dcjl-k0wh7uhynx-rpc.kr0-aws.kaleido.io/"
    rpcEndpoint: "http://127.0.0.1:7545/"
    user: "k0h6brqo7d"                                       # only for kaleido
    password: "x39gQGJj_vv1Dxv8pixtZOWNmALi9tYzypBZqNGzZp8"  # only for kaleido
    accountAddress: "0xcfe1b029bf174b4a713f540e19044536c7f36261"
  contract:
    address: "0x59bb406754216Bd529151C0E9892308c446E8d24"


